/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-variant": "#f9dcd8",
        "on-surface": "#271816",
        "error": "#ba1a1a",
        "secondary-fixed": "#ffe08b",
        "primary-container": "#b71c1c",
        "surface-container-high": "#ffe2de",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#ffcac4",
        "on-tertiary-fixed": "#001c37",
        "outline": "#8f706c",
        "on-tertiary-container": "#bed9ff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d2e4ff",
        "on-error": "#ffffff",
        "surface-container-highest": "#f9dcd8",
        "on-tertiary-fixed-variant": "#00497e",
        "on-secondary-container": "#735a00",
        "on-secondary-fixed": "#241a00",
        "surface-bright": "#fff8f7",
        "surface-container-low": "#fff0ee",
        "inverse-on-surface": "#ffedea",
        "on-surface-variant": "#5b403d",
        "primary-fixed-dim": "#ffb4ab",
        "secondary-container": "#fdd355",
        "surface-dim": "#f0d4d0",
        "background": "#fff8f7",
        "tertiary": "#00487d",
        "surface-tint": "#b91d1d",
        "on-primary-fixed-variant": "#93000b",
        "primary": {
          DEFAULT: "#91000a",
          foreground: "#ffffff",
        },
        "secondary": {
          DEFAULT: "#745b00",
          foreground: "#ffffff",
        },
        "on-secondary-fixed-variant": "#584400",
        "primary-fixed": "#ffdad6",
        "secondary-fixed-dim": "#ebc246",
        "inverse-primary": "#ffb4ab",
        "tertiary-container": "#0060a4",
        "outline-variant": "#e4beb9",
        "on-primary-fixed": "#410002",
        "inverse-surface": "#3e2c2a",
        "on-background": "#271816",
        "surface": "#fff8f7",
        "surface-container": "#ffe9e6",
        "tertiary-fixed-dim": "#a0caff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",

        // Shadcn UI conventional tokens
        border: "hsl(var(--border, 0 0% 89.8%))",
        input: "hsl(var(--input, 0 0% 89.8%))",
        ring: "hsl(var(--ring, 0 84% 28%))",
        muted: {
          DEFAULT: "#f3f4f6",
          foreground: "#6b7280",
        },
        accent: {
          DEFAULT: "#fef3c7",
          foreground: "#78350f",
        },
        card: {
          DEFAULT: "#ffffff",
          foreground: "#271816",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sidebar_width: "260px",
        stack_md: "16px",
        stack_lg: "24px",
        sidebar_collapsed: "72px",
        container_max_width: "100%",
        header_height: "64px",
        margin_desktop: "32px",
        stack_sm: "8px",
        margin_mobile: "16px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
